%% pupilMelanopsinMRIAnalysisRegistryConfiguration
%
% Declare the toolboxes we need for the pupilMelanopsinMRIAnalysis and
% write them into a JSON file.  This will let us use the ToolboxToolbox to
% deliver unto us the perfect runtime environment for this project.
%

% Clear
clear;
% Cleared

%% Declare some toolboxes we want.
config = [ ...
    tbToolboxRecord( ...
    'name', 'BrainardLabToolbox', ...
    'type', 'git', ...
    'url', 'https://github.com/brainardlab/BrainardLabToolbox.git'), ...
    tbToolboxRecord( ...
    'name', 'temporalFittingEngine', ...
    'type', 'git', ...
    'url', 'https://github.com/gkaguirrelab/temporalFittingEngine.git')];

%% Write the config to a JSON file.
configPath = 'pupilMelanopsinMRIAnalysisConfig.json';
tbWriteConfig(config, 'configPath', configPath);